### ISSUE TITLE
Add link to setup

### ISSUE THREAD

**Issue by sscotth** [Smurf-IV/Liquesce#1]
Can you add a link to the setup file in the README or add it to GitHub releases?

**Comment by slrslr** [comment]
yes please, i can not find it

**Comment by snarfsmojo** [comment]
Bump, I also haven't been able to find any release for this code.  I downloaded visual studio CE and attempted to build the project, but ran into a bunch of errors.  I'm not a programmer by trade, so that ended up being a stopping point for me...
Smurf-IV (or anyone else who has a compiled copy of this software) please help?! :)

Thanks much,

Snarfy

**Comment by Smurf-IV** [comment]
These used to exist in CodeProject, but as that has been slowly made into an impossible to use archive, then I'll Add My last set-up to a `releases` area.

I found some from the *Internet archive* and put them in https://github.com/Smurf-IV/Liquesce/releases
No Guarantees on these, I must re-engage with CBFS and see if i can get them to "Lend" me a developer license to recreate this for .Net4.8 on-wards.
